# fly.toml app configuration file generated for golivechattest on 2025-01-11T20:04:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'golivechattest'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
